### ISSUE TITLE
جدا شدن نخسه تیتر از خانواده فونت

### ISSUE THREAD

**Issue by rastikerdar** [rastikerdar/sahel-font#1]
برای اینکه در لیست اسامی فونت ها جداگانه دیده شود. انتخاب حالت تیتر در واژه پرداز مشکل است.

**Comment by zoghal** [comment]
برای این پیشنهاد میکنم یک نگاه به فونت لاله زار بکنی ببینی چگونه متافیلدهاش رو ست کرده. کمکت میکنه.
مشکلی بود بگو برادر.
در ضمن فونت تیترت به اعتقاد من بهترین خروجیت هست. تبریک میگم. :+1:

**Comment by rastikerdar** [comment]
من متوجه نشدم صالح جان! دقیقا چه چیزی منظورت هست آخه لاله زار فقط یه دونه نسخه معمولی داره 
:|

در مورد تیتر هم موافقم بهتر از حالت های دیگرش شده هرچند که از روی همون نسخه معمولی ساخته شده یعنی همونه با ارتفاع بیشتر.

**Comment by zoghal** [comment]
ببینم اول این تاپیک گزارش مشکل هست؟ یا نظر سنجی؟

> در مورد تیتر هم موافقم بهتر از حالت های دیگرش شده هرچند که از روی همون نسخه معمولی ساخته شده یعنی همونه با ارتفاع بیشتر.

راستش اصلا منظورم  این نبود که در بین حالتهای همین فونت بهتر شده. منظورم از کل کارهایی که تا بحال انجام دادید بود.
صابر جان شما زحمت فروانی میکشی، تلاش بسیاری میکنی اما یک نقطه ضعف بزرگ داری، و اون هم این هست به ظرایف طراحی حروف و زیبایی حروف زیاد اهمیت نمیدی. شاید به این خاطره که تمرکزت روی بهتر نمایش داده شدند حروف در سایز ریز هست.

یکبار این رو امتحان کن فرض کن می‌خوای یک بیلبورد طراحی کنی یعنی سایز بالای 150pt . سایر فونت‌هایی که طراحی کردی رو تست بزن ببین  ایا حروفی که طراحی کردی بینشون هارمونی وجود داره. آیا دلچسب خودت هست. مثلا روی ‍ع‍ هات دقت کن.

بعد فونت تیتر ساحل رو تست کن. اولین چیزی که حس می‌کنی اینه که حرکت قلم رو حس می‌کنی.بین  قوس ها و دورها، کنتراست‌ها و تیکنیس‌ها  یک تعادل وجود داره.

لپ کلام روی مسائل هنری و ظرایف طراحی حروف بیشتر کار کن.

**Comment by rastikerdar** [comment]
گزارش یک نوع مشکل بود. یک نفر پیام داده که حالت تیتر یا سیاه رو توی واژه پرداز چجوری انتخاب کنم که باید پنجره دیالوگ فونت بیاره و ...
گفتم جدا بشه راحت تره.

در مورد ظرافت طراحی صالح جان خب حق داری و باور کن من خودم این مشکلات رو میدیدم اما خب کی حال و حول کار حرفه ای رایگان داره :)
این سطحی که مد نظر شماست پول می خواست. مثل پی فونت.
مبنای من همین بحث وب و اپ و اینجور چیزا بود. اما خب چشم سعی می کنم از این به بعد توصیه کاملا به حق شما رو جدی بگیرم و این ظرافت ها رو رعایت و این نقطه ضعف رو برطرف کنم.

البته یه نکته شاید جالب بگم اینه که بیس کار من فونت دژاوو بود. خب این یه جورایی منو بد عادت یا تنبل کرد. تقریبا هیچ گلیفی توی دژاوو درست نیست!
![screenshot from 2016-07-29 06-28-55](https://cloud.githubusercontent.com/assets/3116038/17235387/ec9e68ce-5555-11e6-9a8e-c49a227ed783.png)

تشکر  :)

**Comment by shahabsiavash** [comment]
صابر جان مشکل اینه که سه وزن در ساب فمیلی یک جا لیست نمیشن یا بر عکسش؟

صالح جان فکر کنم دیگه اینها بی‌انصافی باشه. همون که قبلن هم نوشتم و تو مقاله بررسی موج نو هم مواردش رو آوردم فونتهای صابر جان می‌تونه به راحتی کل اینترنت و اپلیکیشنها رو مال خود کنه. فقط همون مشکلاتی که نوشتم اگه حل بشه که ساده هم هست و نمی‌دونم چرا مورد توجه قرار نمی‌گیره. 

علائم و نشانه‌ها و حروف انگلیسی که می‌تونه از فونتهای آزاد دیگه برداشته شه. 

خانواده ساحل همه‌شون خوبن ولی چون ما فونت سیاه خوب کم دیدیم بیشتر از سیاه خوشمون اومده وگرنه بقیه وزنها هم چیزی کم ندارن. اگه مواردی که لازم هست هر فونت استانداری داشته باشه اعمال شه به راحتی بقیه فونتهایی که الان هست و یکیشون رو اینقدر دیدیم خسته شدیم به کنار میرن با توجه به اینکه فونتهای صابر جان چند تا هست در وزنهای مختلف. :)

**Comment by rastikerdar** [comment]
اینکه مثلا توی وورد شما بخوای متنی رو بولد کنی راحت دکمه بولد رو میزنی و خودش میره حالت ضخیم از خانواده فونت رو لود می کنه. اما اگر بخوای تیتر یا همان سیاهش کنی باید گزینشو توی پنجره ها پیدا کنی. حالا اگر ما اینو از خانواده جدا کنیم قاعدتا توی لیست اصلی فونت ها به عنوان یک قلم جداگانه با یه اسم جدیدی که گذاشتیم میاره. مثلا ساحل تیتر. برای حالات نازک و غیره هم همین رویه صدق می کنه.
البته این چیزیه که به ذهنم میرسه.

در مورد علائم و ... هم حق با شماست. البته مدتیه نسخه جدیدی از فونت ها نیامده. توی نسخه آتی هر کدام از فونت‌ها حتما این موارد لحاظ میشه. فکر می کنم اوپن سنس و روبوتو مناسب باشند.

**Comment by shahabsiavash** [comment]
بله درسته. تا جایی که به خاطر دارم تا آفیس ۲۰۰۷ از هیچکدام از استایلها و سابفمیلی ها پشتیبانی نمیکنه و فقط بولد و ایتالیک رو میفهمه. تو خیلی از فورومها اعتراض میشد که نهایتن گویا در ۲۰۱۳ یا ۲۰۱۶ یه تغییراتی دادن که بیشتر شامل پشتیبانی از سالت و کالت و ویژگی‌های اپن تایپ میشد که قبلن اینا رو هم نداشت. ولی وزنها رو فکر کنم هنوز هم نداره غیر از بولد و ایتالیک.

بله فونتهایی که گفتین به نظر منم هماهنگ هستن.

**Comment by zoghal** [comment]
> صالح جان فکر کنم دیگه اینها بی‌انصافی باشه. همون که قبلن هم نوشتم و تو مقاله بررسی موج نو هم مواردش رو آوردم فونتهای صابر جان می‌تونه به راحتی کل اینترنت و اپلیکیشنها رو مال خود کنه. فقط همون مشکلاتی که نوشتم اگه حل بشه که ساده هم هست و نمی‌دونم چرا مورد توجه قرار نمی‌گیره.

ای بابا :)) بی انصافی دیگه واسه چی من که ایراد نگرفتم. تشویق کردم حالا که داری این همه زحمت می‌کشی کمی وقت و تلاش بیشتر برای بهتر شدن چهره حروف از لحاظ تخصصی گرافیک  و سوق پیدا کردن به سمت حرفه ای شدند و بهتر شدن بود. نه ایراد گیری.

> فونتهای صابر جان می‌تونه به راحتی کل اینترنت و اپلیکیشنها رو مال خود کنه. 

این به نظرم  انتهاش سکون و درجا زدن ختم میشه .اصلا  چرا همین دو مورد؟  سایر موارد دیگر هم باید مد نظر داشت. در اصل نگاهی به آینده حرفه ای باعث رشد و ترقی میشه.

> در مورد ظرافت طراحی صالح جان خب حق داری و باور کن من خودم این مشکلات رو میدیدم اما خب کی حال و حول کار حرفه ای رایگان داره :)

عزیزجانم شما که داری زحمت میکشی وقت صرف می‌کنی، کمی تلاش بیشتر به نفع خودت تموم میشه. اگر پروژه پی فونت رو حرفه‌ای میدونی شدیدا در اشتباهی تایپ فارسی تازه در ابتدای راهش هست. نوظهور هست. خیلی جای رشد و ترقی داره.

این دو مطلب رو خوب گوش کن : [این ](http://pesign.ir/index.php/2016/02/18/typography-panel-part-i/)و [این](http://pesign.ir/index.php/2016/02/25/typography-panel-part-ii/) دید بهتری بهت میده.

> البته یه نکته شاید جالب بگم اینه که بیس کار من فونت دژاوو بود. خب این یه جورایی منو بد عادت یا تنبل کرد. تقریبا هیچ گلیفی توی دژاوو درست نیست!

آخ گفتی ضمن اینکه به نکته درستی اشاره کردی واجب هست این نکته رو بگم که بابا شما استارت رو بر اساس این فونت شروع کردی تموم شد رفت.  در حال حاضر بیشتر حروف رو خودت طراحی می‌کنی یا از از منابع دیگه ایده اولیه میگیری و حروف خودت رو طراحی می‌کنی کم بگو بر اساس این فونت انجام شده. اعتماد به نفس داشته باش.

نکته آخر اینستاگرام [من](https://www.instagram.com/saleh.souzanchi/) رو زیر نظر بگیر فیلم های جدیدی از نحوه طراحی حروف شروع به انتشار میکنم.اگر خدا بخواد مشکل سیستمم بالاخره حل شد

**Comment by rastikerdar** [comment]
در نسخه جدید جدا شد. با تشکر از دوستان
