### ISSUE TITLE
بازنگری در مورد مجوز ofl

### ISSUE THREAD

**Issue by zoghal** [rastikerdar/sahel-font#10]
درود 
دیدم در صفحات پرزنت ذکر کردی که: 

> مجوز OFL به طور خلاصه می‌گوید شما اجازه استفاده از قلم در هر کاری چه شخصی و چه تجاری خواهید داشت منوط به اینکه در صورت تغییر آن را مجددا بازنشر نمایید.

در صورتی که در مجوز ofl همچین اجازه ای اصلا داده نشده. پیشنهاد میکنم یک وقت بزاری این لایسنس مخصوصا بخش 3 MODIFYING OFL-LICENSED FONTS رو خوب مطالعه کنی، اگر بتونی زحمت ترجمش رو هم بکشی که عالی میشه. نیاز داریمش :)
مخلص

**Comment by rastikerdar** [comment]
صالح جان متوجه منظورت دقیقا نشدم!

> The OFL allows the licensed fonts to be used, studied, modified and
> redistributed freely as long as they are not sold by themselves.

ببین صالح! این میگه او اف ال به فونت های تحت این مجوز اجازه میده آزادانه مورد استفاده، مطالعه، تغییر و بازنشر قرار بگیرند مادامی که خود فونت ها به فروش نرسند.

> 3) No Modified Version of the Font Software may use the Reserved Font
> Name(s) unless explicit written permission ...

توی بخش ۳ هم که فرمودی در واقع اشاره به رزرو بودن نام فونت کرده که نباید توی نسخه های مشتق شده یا تغییر یافته استفاده بشه مگر با اجازه مکتوب و صریح.

توی بخش ۵ هم اشاره کرده که نسخه اصلی یا تغییریافته باید تنها تحت همین مجوز و نه هیچ مجوز دیگری توزیع یابند.

پ.ن. در مورد ترجمه خیر بنده چنین کاری نمی کنم :)

**Comment by zoghal** [comment]
یعنی الان که مجدد دارم می‌خونم باورم نمیشه همچین سوتی داده باشم. اما خوب دادم دیگه. کلمه تجاری رو من فروش قلمداد کردم گویا.
خاک بریز روش :)))
