### ISSUE TITLE
ExHeight is zero

### ISSUE THREAD

**Issue by bateni** [rastikerdar/sahel-font#12]
در قلم‌هایی که تولید کردی، مقدار این پارامتر صفره و باعث می‌شه در نرم‌افزار TeX به مشکل بر بخورم.  این پارامتر در واقع ارتفاع یک حرف x انگلیسی را مشخص می‌کند و برای برخی محاسبات به کار می‌رود، مثلاً تعیین ارتفاع مناسب برای نشانه پانوشت.

Menus: Element -> Font Info -> TeX -> XHeight

**Comment by rastikerdar** [comment]
از شما تشکر می کنم برای گزارش این اشکال. در نسخه جدید مرتفع شد. اگر باز هم مشکلی بود بفرمایید.
