### ISSUE TITLE
ایراد در طراحی گلیف « ـکـ » در وزن تیره

### ISSUE THREAD

**Issue by artlesshand** [rastikerdar/sahel-font#14]
<div dir="rtl">
خسته‌نباشی صابر عزیز؛<br />
گلیف «ـکـ» یا همون کاف وسط در وزن تیره (۹۰۰) یک خط اضافی نازک روش داره
</div>
<img src='https://cloud.githubusercontent.com/assets/763112/21580513/b36fd0c4-d011-11e6-8fd9-e701af2a282b.png'>

**Comment by rastikerdar** [comment]
آقا فرزان خیلی ممنونم برای گزارش این ایراد. توی نسخه جدید برطرف شد.

**Comment by artlesshand** [comment]
<div textalign="right" dir="rtl">
قربانت صابر جان :)<br />
ممنون از زحماتت.
</div>
