### ISSUE TITLE
درخواست افزودن font-weight: 300

### ISSUE THREAD

**Issue by sdns** [rastikerdar/sahel-font#16]
فونت ساحل فونت بسیار عالی هست. من در وب تست کردم فونت خیلی خوبی هست. فقط اگه
font-weight 300
 رو هم بهش اضافه کنید تا در تایپوگرافی های نازک هم بشه استفاده کرد خیلی خوب می شه.

**Comment by rastikerdar** [comment]
وزن نازک در سری سوم فونت اضافه شد. با تشکر از پیشنهادتون
[rastikerdar.github.io/sahel-font/](https://rastikerdar.github.io/sahel-font/)
