### ISSUE TITLE
مشکل در نمایش اعداد لاتین

### ISSUE THREAD

**Issue by ho3ein-mola** [rastikerdar/sahel-font#19]
امکانش هست وقتی کسی عددی رو انگلیسی وارد میکنه اعداد به لاتین باشن وقتی فارسی تایپ میکنن فارسی بشه .
الان در همه حالت ها اعداد فارسی وجو نداره

**Comment by rastikerdar** [comment]
اگر درست متوجه شده باشم این به دلیل تعریف نوع صفحه‌کلیدتون (نرم‌افزاری) هست. مثلا کیبورد دسکتاپ من در لینوکس اینطوری هست که اعداد نامپد در هر حالت انگلیسی تایپ می‌شوند اما اعداد بالای حروف بسته به نوع زیان تغییر می‌کنند. به عبارتی این موضوع به خود فونت مربوط نمیشه بلکه به تعریف کیبورد وابسته هست.

**Comment by ho3ein-mola** [comment]
تشکر از جواب شما . الان امتحان کردم در لینوکس هم هر دو حالت اعداد فارسی هستن . کدوم بسته  هردو عدد رو داره ؟

**Comment by rastikerdar** [comment]
از نسخه ای که تمام ارقامش فارسی هستید استفاده نفرمایید. اونی که
FD
داره یعنی تمامی اعداد اعم از عربی و انگلیسی به صورت فارسی باشند.
البته پیشنهاد می‌کنم از نسخه جدید قلم استفاده کنید.
