### ISSUE TITLE
دو مشکل مهم فونت ساحل

### ISSUE THREAD

**Issue by abbasnaqdi** [rastikerdar/sahel-font#21]
سلام . همانطور که در بخش فونت وزیر گفتم فونت ساحل بهترین فونت برای صفحات وب و فونت وزیر بهترین فونت برای اپلیکیشن های اندروید هست اما چند ایراد فونت ساحل داره که تصمیم گرفتم عنوان کنم تا اصلاح کنید .

مشکل اول : بزرگترین مشکل این فونت این هست که نسخه بولد این فونت اصلا هماهنگ و شباهتی با نسخه معمولی این فونت نداره و باید بگم خیلی زشت و بد ریخت هست نسخه بولد ساحل مخصوصا داخل موبایل ها افتضاحه خیلی بده خیلی باور کنید :)

مشکل دوم : فونت رو تغییر رنگ دادم با رنگ قهوه ای تیره و متاسفانه با کمی دقت مشاهده کردم نقطه مرزی چسپیدن حروف با هم معلومه و با رنگ مشکی هست در واقع از دور معلوم نیست و از نزدیک مشخصه کاملا .

میشه گفت ساحل از فونت وزیر خوش ساخت تر هست متنهی اگر این مشکلات رو رفع کنید عالی میشه برای وب با تشکر .

**Comment by rastikerdar** [comment]
سلام
در مورد مشکل اول حق با شماست اما راستش بضاعت من هم همینقدر است. در حال حاضر شکل بهتری به ذهنم نمی‌رسد اما سعی می‌کنم اگر به نتیجه‌ای رسیدم انجام دهم

در مورد مشکل دوم هم کاملا حق با شماست اما این مشکل به خاطر همپوشانی گلبف‌ها جهت جلوگیری از ایجاد فاصله در هنگام رندر به وجود میاد. در اغلب فونت‌ها چنین مشکلی وجود دارد. فعلا باید امیدوار به روزی بود که شیوه‌های جدید رندر بتوانند ما رو از ایجاد ناحیه همپوشانی بی‌نیاز کنند.

**Comment by rastikerdar** [comment]
من از اون موقع سعی کردم یک سری بهبود در حالت ضخیم انجام بدم نمی‌دونم در حدی باشه که بتونه نظر شما رو تامین کنه یا نه:
[rastikerdar.github.io/sahel-font/test.html](https://rastikerdar.github.io/sahel-font/test.html)
بالای صفحه حالت ضخیم رو انتخاب و با معمولی مقایسه کتید.

 در صورت امکان نیز بفرمایید حالت ضخیم چه فونتی بیشتر مد نظر و مطلوب شماست تا شاید بتوان از روش اون الگو گرفت.

**Comment by abbasnaqdi** [comment]
سلام. ممنونم از حسن توجه شما. عالیه 

فونت رو برسی کردم حس میکنم فونت بهتر شده به صورت کلی نمیدونم نسخه ای هست که من قبلا دیدم یا آپدیت کردین .
`
در حالت ذخیم بعضی کلمات وزن یکسان ندارن مثلا به حرف ل نگاه کنید در فونت ساحل . در نسخه معمولی تمام خط یک وزن داره ولی در نسخه ذخیم نه و وزن کم و زیاد میشه .`

**البته هنوز نمیدونم اینکه همه کاراکتر ها وزنشون یکی باشه زیبا تر میشه یا نه ولی فکر میکنم برای خوندن چشم رو بهتر درک میکنه . 
چیزی که میتونم بگم اینه عالیه در نسخه فعلی . ممنونم از شما و دستتون درد نکنه .**

**Comment by rastikerdar** [comment]
به نکته خوبی اشاره فرمودین. چیزی که باعث میشه طراحی فونت‌های مثل ساحل، پرستو، میترا و امثالهم بسیار دشوار بشه یکسان نبودن ضخامت‌‌هاست. نسخه ضخیم به نوعی دوباره ساخته می‌شه. همچنین نسخه تیتر. اما در مورد فونت وزیر یا شبنم این‌گونه نیست و ساخت اوزان متعدد برای اون‌ها کار راحت‌تریه.
توی تصویر زیر شکل پایین حالت فعلی ساحل هست اما برای شکل بالا هیچ کاری صورت نگرفته و فقط خود نرم‌افزار اون رو ضخیم‌تر کرده.
![sahel](https://user-images.githubusercontent.com/3116038/43088971-be854158-8eb8-11e8-9ca2-0af5d2fb22f3.png)

اما اینکه کدام بهتره حقیقتش نمی‌دونم.

**Comment by abbasnaqdi** [comment]
به نظرم میرسه یکسان بودن خط ها خوانایی نوشته هارو در متن های طولانی بیشتر میکنه .
باید تست کرد . انشالله فونت بعدی درست شد سعی کنید این رو امتحان کنید داخلش :)

**Comment by rastikerdar** [comment]
فونت بولد عمدتا برای عناوین و متون کوتاه به کار میره و جنبه تاکیدی داره. و البته چون بزرگ‌تر و درشت‌تر نمایش داده می‌شه ظرافت‌ها یا اشکالاتش بیش‌تر به چشم میاد. این نوع قلم‌ها در دسته نسخ قرار می‌گیرند. اما اگر تنها موضوع متن طولانی آن هم در صفحات نمایش مطرح باشه قطعا همانطور که می‌فرمایید ضخامت یکسان نتیجه بهتری ارائه میده.

در مورد فونت جدید هم پیشنهاد خوبیه. بودجه از شما، کار از من
:D
