### ISSUE TITLE
 جدا شناخته شدن ضخامت بلک از دو ضخامت رگلار و بولد در نرم‌افزارها

### ISSUE THREAD

**Issue by ho3in52** [rastikerdar/sahel-font#23]
سلام خداقوت واسه انتخاب ضخامت Black فونت ساحل توی لیست ضخامت ها نمیاد و فونت Sahel Black یه فونت جداگانه توی نرم افزار ها معمولا شناخته میشه و بعضی وقتها واسه تغییر از ضخامت Regular یا Bold به Black کمی رو اعصابه. :)

مجدد خداقوت جناب راستی کردار فونت بسیار زیبایی هست این فونت
![photoshop font select](https://user-images.githubusercontent.com/14910155/50722655-8f596100-10e7-11e9-8860-47333017a4c2.png)

**Comment by rastikerdar** [comment]
سلام
حق با شماست. البته این کار برای دسترسی راحت‌تر به وزن سیاه در برنامه‌هایی مثل آفیس وورد صورت گرفته اما قاعده اصلی همان است که فرمودید.
