### ISSUE TITLE
جابه‌جاشدن حرف ه-تنها با آمدن یای کوچک

### ISSUE THREAD

**Issue by iriman** [rastikerdar/sahel-font#26]
<div dir="rtl">
سلام 

در کلماتی مثل گهواره که ه به‌شکل تنها می‌آید اگر همزه اضافه کنیم یا کلاً نویسهٔ ۀ را به‌کار ببریم، حرف ه جابه‌جا می‌شود. این تصویر گویاتر است:

![heh](https://user-images.githubusercontent.com/8467903/57975194-e8140100-79d9-11e9-8e1f-e27c024164f3.gif)

آزمایش بالا را در صفحهٔ [test2](https://rastikerdar.github.io/sahel-font/test2.html) انجام دادم.

ممنون که این فونت زیبا را ساخته‌اید.

**Comment by rastikerdar** [comment]
سلام
ممنونم برای گزارش این ایراد.  در نسخه آتی برطرف خواهد شد.

**Comment by typoman** [comment]
همزه برای فارسی نیست و اون کاراکتر که شما گفتید اصلن اِعراب نیست. به این شکل باید نوشته بشه: «نویسه‌ی». لطفن در فارسی استفاده نکنید:

> ۀ is the fortieth letter of Pashto alphabet. It represents the vowel (IPA: /ə/) and is transliterated ⟨ë⟩.[1] It is known as Kajira He. 

https://en.wikipedia.org/wiki/%DB%80

**Comment by rastikerdar** [comment]
آقای اسلامی اگه اشتباه نکنم اون شیوه منتفی شده و برگشته به حالت سابق.

**Comment by typoman** [comment]
یعنی با کدوم کاراکتر اون «ی» الآن تایپ می‌شه؟ همزه؟ می‌شه تایپ کنید؟ من یه مقدار از نحو‌ه‌ی کنونی نگارش فارسی شاید عقب افتاده باشم.

**Comment by typoman** [comment]
اینو پیدا کردم راجع به نقش‌نمای اضافه. به نظرم میاد که از همزه هم در ویکی‌پدیا استفاده می‌شه که مغایرت داره با هدفی که برای این کاراکتر در نظر گرفته شده بود. مرسی آقای راستی‌کردار.
https://fa.wikipedia.org/wiki/%D9%86%D9%82%D8%B4%E2%80%8C%D9%86%D9%85%D8%A7%DB%8C_%D8%A7%D8%B6%D8%A7%D9%81%D9%87

**Comment by typoman** [comment]
اگر این قلم برای متن فارسی استفاده بشه ایرادی نداره، اما اگه برای زبان‌های دیگر (مانند عربی) استفاده بشه یک راهی باید داشته باشه که شکل همزه حفظ بشه وگرنه خواننده‌ها با فرم عجیبی از همزه مواجه خواهند شد.

**Comment by rastikerdar** [comment]
درسته. الان من هم دچار تردید شدم که خب برای زبان عربی به مشکل بر می‌خوریم. هممم راه‌حل چیه؟

**Comment by typoman** [comment]
من این مشکل رو توی گروه محاسبات فارسی مطرح کردم ببینیم چه راه حلی پیدا می‌شه. پستم یه مقدار طول می‌کشه که قبول بشه:

https://groups.google.com/forum/?hl=fa#!forum/persian-computing-fa

**Comment by typoman** [comment]
پیشنهاد من این هست که شکل همزه وقتی بالا‌ی اشکال «‍ه» می‌آد به گلیفی که به شکل «ی» کوچک هست تغییر داده بشه، این گلیف «ی» کوچک نباید یونیکد داشته باشه. این اتفاق بهتره فقط توی فارسی بیفته اما چون احتمال اینکه کاربر زبان رو روی فارسی بگذاره کمه، لزومی به این محدودیت نیست. شکل همزه باید حفظ بشه در حالت پیش فرض.

**Comment by rastikerdar** [comment]
پس همین حالتي که الان هست درسته. چون این حالت و لیگچر تنها برای زبان فارسی وجود داره

**Comment by typoman** [comment]
چه عالی، نمی‌دونستم شکل پیش فرض همزه حفظ شده. شاید این بحث منبعی بشه برای کسی که سوال شبیهی داره.

**Comment by rastikerdar** [comment]
در نسخه جدید این اشکال رفع گردید.  با تشکر از شما  
[github.com/rastikerdar/sahel-font/releases](https://github.com/rastikerdar/sahel-font/releases)
