### ISSUE TITLE
گیومهٔ فارسی

### ISSUE THREAD

**Issue by afshin-ir** [rastikerdar/sahel-font#32]
<div dir=rtl>
سلام. 

گیومهٔ فارسی در فونت ساحل مشابه گیومهٔ عربی طراحی شده است، یعنی شبیه علامت کوچک‌تر و بزرگ‌تر است و سر علامت‌ها هم نوک‌تیز است. 
گیومهٔ فارسی شبیه پرانتزهای کوچک است و سر پرانتزها هم نرم است.

**Comment by rastikerdar** [comment]
سلام
تشکر می‌کنم برای ایشو
در نسخه ۳ برای گیومه شکل جدیدی طراحی شد. البته سر پرانتزها رو نمی‌شد نرم کرد چون با فرم حروف تناسب نداشت.
![Screenshot at 2019-10-30 15-18-29](https://user-images.githubusercontent.com/3116038/67855874-93e47f80-fb28-11e9-844f-11640096e32f.png)

**Comment by afshin-ir** [comment]
<div dir=rtl>
خیلی تشکر می‌کنم بابت زحمتی که کشیدید.

**Comment by afshin-ir** [comment]
<div dir=rtl>
سلام.

من در نسخهٔ دسکتاپ تلگرام و سیستم‌عامل گنو/لینوکس از همین فونت استفاده می‌کنم. 
عجیب است که با اینکه نسخهٔ ۳ را هم نصب کرده‌ام، باز هم گیومهٔ فارسی را به‌صورت قدیم، یعنی «لبه‌تیز» نمایش می‌دهد. 
در بقیهٔ برنامه‌ها صورتِ جدید گیومه است و مشکلی وجود ندارد.

**Comment by rastikerdar** [comment]
سلام
شاید داره از نسحه کش شده استفاده می‌کنه
شاید این دستور به درد بخوره
`$ fc-cache -rv`

**Comment by afshin-ir** [comment]
<div dir=rtl>
دستور را اجرا کردم. حتی بعدش سیستم را ری‌استارت کردم؛ ولی بی‌فایده بود! واقعاً عجیب است.
