### ISSUE TITLE
نمایش جدا جدای (نامتصل) حروف نسخه متغیر در نرم افزار ایلستریتور

### ISSUE THREAD

**Issue by rastikerdar** [rastikerdar/sahel-font#37]
پیام آمده در [وبلاگ](http://rastikerdar.blog.ir/1395/05/01/%D9%82%D9%84%D9%85-%D9%81%D9%88%D9%86%D8%AA-%D9%81%D8%A7%D8%B1%D8%B3%DB%8C-%D8%B3%D8%A7%D8%AD%D9%84#comment-0Xi7WozQP8o) از طرف امیرمحمد:
> در نسخه‌ی جدید ساحل که وریبل‌فونت اضافه شده، توی ایلستریتور ۲۰۱۹ کاراکترها جدا نوشته می‌شن؛ مثلا یه متن عادی می‌شه «ی‌ه م‌ت‌ن ع‌ا‌د‌ی»، در حالی که با وزن‌ها و انواع دیگه‌ی ساحل، این مشکل نیست.
توی فوتوشاپ ۲۰۱۹ هم نتونستم از وریبل‌فونت استفاده کنم.
لازمه بگم که تنظیمات تایپ فارسی توی هر دو نرم‌افزار رو انجام دادم و مشکلی با فونت‌های دیگه ندارم

**Comment by aminabedi68** [comment]
مشکل مربوط به خود ادوبی بود که تو نسخه‌های بعد برطرف شده
