### ISSUE TITLE
نسخه جدید فوق‌العاده ست!

### ISSUE THREAD

**Issue by shahabsiavash** [rastikerdar/sahel-font#7]
صابر جان خسته نباشی. به جرات می‌شه گفت خانواده **`ساحل`** یکی از قوی‌ترین خانواده‌های فونت فارسی هست.

لطفن در صورت تمایل حتمن این خانواده رو در **`گوگل فونتز`** عرضه کن. با توجه به اینکه حالا شرایطش رو هم داره با حروف لاتین و علامات. بسیاری از فارسی‌زبانان و عرب‌زبانان می‌تونن از این خانواده استفاده کنن. مخصوصن که سه وزن مختلف داره و برای وب عالی هست.

ایده اضافه کردن ه و ـه با شش کوچیک یا یای کوچیک به عنوان لیگچر هم عالی بود.

بسیار عالی و خسته نباشی.

**Comment by rastikerdar** [comment]
اولا شما خیلی لطف داری سیاوش جان.
ثانیا ای بابا این کارها واسه آدم نون و آب نمیشه.
ثالثا برای اونجا یه سری ملزومات تعیین شده. این قلم هنوز در طراحی نیاز به اصلاحات داره و همچنین گلیف های دیگر زبان ها.
رابعا فکر نمی کنم مورد پسند عموم قرار گرفته باشه. به نظر تایپ فیس قلم دلچسب نیست.

سلامت باشید.

**Comment by zoghal** [comment]
> رابعا فکر نمی کنم مورد پسند عموم قرار گرفته باشه. به نظر تایپ فیس قلم دلچسب نیست.

ایییییش دلشون هم بخواد. یک نگاه به فونت های عربی بندازی و مقایسه کنی به این ۱۰۰ میدی .

**Comment by shahabsiavash** [comment]
من متوجه شدم که صابر جان از تعریف و تمجید خوششون نمیاد یا شاید معذب میشن :) ولی من رو کسایی که میشناسن میدونن که تعریف همین جوری نمیکنم. معروف ترین فونتها به نظرم مشکلات زیادی دارن و باید نوشت و گغت. من خودم هم دوست داشتم که بقیه با توجه به در نظر گرفتن اینکه فونتهای من مخصوص نوشتار و نشر رومیزی نیستن راجع بهشون بگن و بنویسن. خیلیا اساسن سوادش رو ندارن و سریع میان مینویسن با اینا که نمیشه کتاب چاپ کرد! دیگه چه میشه گفت؟

متاسفانه فوروم‌های ایرانی همون جوری که قبلن هم بهم ثابت شده بود و سالها فراری بودم ازشون تا اینکه اومدم گیت هاب و اینا، همش دنبال حاشیه و پلیس‌بازی هستن و در طول شاید ده سال گذشته دریغ از یک همفکری و انتقاد مفید. نمونه‌ش دفعه پیش بود که کلن بحث بیهوده و بی‌فایده‌ای در گرفت و وقت و انرژی همه رو هدر داد. بدیهیاتی رو باید توضیح داد که واقعن از حوصله و انرژی من خارجه. 

من هم دوباره برگشتم به دوران قبل و با فورومها و گروههای ایرانی کاری ندارم چه ایرماگ چه فونت آزاد و چه توییتر. سه تا پست تو تایپ‌دراوور خارجی گذاشتم اندازه یک سال چیز یاد گرفتم. بنابراین عاقلانه است که وقتم رو اونجا بذارم.

راستی صالح یا صابر جان اگه دوست داشتین یک گروه فونت **واقعن** آزاد راه اندازی کنین که اونجا همه کسایی که به فکر فونت آزاد هستن بیان. خیلی بهتره تا اونجا که بوی باندبازی میده. من اساسن چهار فونتم رو تغییر لایسنس دادم و آوردم اونجا گذاشتم واسه همین که ملت در موارد خاص استفاده کنن. وگرنه چه سودی برای من داره که فونت من رو بذارن یا نذارن؟ اهمیتی نداره. تو پی‌سی‌دانلود و دانلودها و فونت‌لایبری و سایت خودم و خیلی جاهای دیگه هست. هر کی بخواد پیدا میکنه خودش. هر سایت خارجی فونت آزاد تو پنج دقیقه میشه فونت آپ کرد. متاسفانه ایرانی‌ها اخلاق‌های غریبی دارن. یا از این ور بوم یا از اون ور! یه مدت که همه کپی‌کار بودن الان برای من چنان لایسنس‌خوان و سورس‌خواه شدن که گوگل فونتز اینجوری نیست. خیلی از فونتهای روی گوگل اصن سورس ندارن و فقط فایل فونت هست. این اخلاقا و ادعاهای مثلن ما خیلی به روز شدیم و قانون داریم حوصله‌مو سر می‌بره چون حاشیه‌ست تا اصل.

 چقدر حرف زدم :)) راستی این مخلوطی بود از اینجا و اونجا که دیگه چون اونجا نمیرم اینجا نوشتم. اگه دوست نداشتین پاک کنین.

به هر حال موفق باشید :)

**Comment by rastikerdar** [comment]
@سیاوش

۱. من روز نخستی که فونت های شما رو دیدم به چشم کار گرافیکی نگاه می کردم. یعنی اولین چیزی که به ذهنم می رسید این بود که این فونت ها کاربردشون عمومی نیست و مناسب گرافیست ها و کارهای هنری می باشد.

۲. همیشه در نظر داشته باشید سلیقه عام یا غالب جامعه در یک طیف تقریبا مشخص قرار دارد. این در اغلب مسائل زندگی صدق می کند. پس اگر می خواهد خارج از این طیف تحرکی داشته باشید به هیچ وجه نباید انتظار همراهی حتی اندک افراد رو هم بکشید. می توانید به بیرون آن گریز بزنید اما این منوط به قرار گیری بخش اعظم سلیقه شما در آن طیف عمومی است. این فی نفسه چیز بدی نیست. صرفا قاعده بازی بدین گونه است.

۳. جامعه ما با جوامع غربی تفاوت محسوسی دارد. هم در سطح هم در ساختار. سطح از این بابت که آنها از خیلی مسائل عبور کرده اند و نگاهشان به دنیای پیرامونی متنوع تر شده است. این را در همه شئون زندگی آنها می بینید. هنر، ادبیات، علم، ارتباطات و ... 
ساختار نیز از آن بابت که اصول و مبانی فکری و عقیدتی آنها با ما تفاوت زیادی دارد. به عبارتی حتی اگر هم سطح هم شویم باز در بسیاری سلیقه ها و نگاه ها در تضاد خواهیم بود. این موضوع خیلی پیچیده هست.

۴. سیاوش جان، دوستان توی گروه فونت آزاد افرادی بااخلاق، تعامل گر و حرفه ای هستند. شما در قسمت ایشوهای فونت صمیم و شبنم این را به وضوح می توانید ملاحظه بفرمایید. صمیمانه عرض کنم فضای گفت و گو در آنجا تا حدودی متاثر از ادبیات شما بود. اگر چه من شما رو درک می کردم اما خب فکر می کنم شاید بهتر بود کمی ملایم تر می بودید.

خلاصه این که زیاد سخت نگیرید. به قول خودتون تهش هیچ چیز خاصی نیست. مهمتر از همه اینها اون آرامش و اعصاب آدمه که نباید آسیب ببینه.

**Comment by shahabsiavash** [comment]
@rastikerdar 

ممنون صابر جان

۱- خیلی ممنون

۲- ببینید من واقعن انتظار همراهی و تعریف و تمجید و اینها نداشتم و ندارم واقعن. این هم مربوط به غرور و اینها نیست. برای اینکه می‌دونم که در فضای ایرانی خیلی خیلی دشوار هست که شما این گزاره رو جا بندازین که «همه قرار نیست یک کار بکنن یا یک جور اون کار رو بکنن» مردم حتا در موارد دیگر هم همین طور هستن. یا اون جوری که ما انتظار داریم یا دیگه کلن از ریشه بزنیم بره.

۳- این بخش رو در واقع قبول ندارم. اگر پیش‌فرض تفاوت جامعه‌ها رو در این حد بپذیریم پس حق هم نداریم با همون قوانین دیگران رو قضاوت کنیم. خیلی ساده ست. یا شما دم از کپی‌رایت باید بزنید و اون وقت چون قانون بین‌المللی هست رعایتش کنین و یا دیگه نمی‌تونین هر چی رو که دوست دارین انجام بدین و اون وقت مدعی‌العموم هم باشین در این امر.

مثالی که من بیشتر اوقات می‌زنم و اونجا هم مختصر اشاره کردم و در ایرماگ هم گفتم و قاطی کردن یکیش همین فارسی‌سازها هستن.
شرکت مریم‌سافت در تمام برنامه‌ها و از جمله قلم برتر تمام فونتها رو به اصطلاح دزدیده. نه تنها میترا و نازنین و بدر و یاقوت و زر رو که هنور هم مشمول کپی‌رایت لاینوتایپ و مونوتایپ هستن و صدها دلار قیمت مجموعشون میشه و جریمه و خسارت تغییر دادنشون به صدها هزار دلار می‌رسه بلکه به فونت تقریبن متاخر ادوبی عربیک هم رحم نکرده و اسمش رو عوض کرده و همه اینها رو به بهانه اضافه کردن امکانات تایپوگرافی داره می‌فروشه صد هزار تومن. 
البته لطف دیگه‌ای هم کرده و کدپوینت رو تغییر داده که هیچکس نتونه ازشون استفاده کنه بدون قلم برتر. یعنی به هر دلیلی ساپورت قلم برتر متوقف شه در سالهای آینده کاربران ممکنه صدها صفحه مطلب رو از دست بدن چون نه متن یونیکد استاندارد هست و نه قابل سرچ و نه هیچی.
خب الان عکس‌العمل همون سینه‌چاکان کپی‌رایت چیه؟ هیچی! تازه تعریف و تمجید و سوت و کف هم نثار مریم‌سافت میشه. من هیچ مشکلی با مریم‌سافت ندارم حتا مدیرش تقریبن موافق قرار دادن فونتهای من بود در بسته اما از لحاظ فنی مشکل داشتن و دارن.
به علت بلایی که سر فونتها میارن که احتمالن برای فونتهای من عملی نیست. شاید راجع به مهندسی معکوسی که از فونتهای قلم برتر کردم بعدتر نوشتم.
خب اگه ازشون بپرسی که چطور یه بابایی یه فونت رو برداره واسه نوشتن خاطرات روزانه مثلن، شماها بهش حمله می‌کنین. اونوقت یه شرکت که داره محصول زحمت دیگران رو صد هزار تومن اونم با قفل و تغییر کدپوینت می‌فروشه کارش قانونیه؟
اینجاست که ترش می‌کنن و حاضر نیستن جواب بدن و فقط میگن که باید از حقوق تولید کننده دفاع کرد!
میگن کپی‌رایت داریم و من به شدت می‌گم هنوز هم که نداریم. چار تا قانون و دو تا معاهده که ایران امضا کرده که نشد کپی‌رایت. ایران خیلی چیزها رو امضا می‌کنه. حقوق بشر و آزادی مطبوعات و... خیلی قانونها هم هست که تصویب می‌کنه اما هیچکدوم انجام نمی‌شه.
همین فردا شما می‌تونی بری وزارت ارشاد مملکت به طور قانونی مجوز تولید صدها هزار دلار نرم‌افزار کرک شده رو بگیری و تولید کنی به طور قانونی. 
چیزی که متعصبین رگ گردن بر آمده‌ی چهار روزه‌ی کپی‌رایت درک نمی‌کنن اینه که اینا رو من واسه این نمیگم که مجوز بدم همه برن همه چی رو کپی کنن. نه! اینو واسه این میگم که تا وقتی ما مشکل رو درست نشناسیم راه حلش هم همین جوری که الان هست دیمی و مضحکه.
این که هر وقت من خودم یا رفیقم یا شرکت دوستم طراحی کردیم داد و هوار کنم که کپی رایت ولی برنامه‌ای که ازش استفاده می‌کنیم فونت‌لب یا ادوبی ایلوستریتور یا خود ویندوز و... همه دزدی. بهانه چیه؟ آخه ما تحریمیم و نمی‌تونیم بخریم! یعنی اگه تحریم نبود آقایون می‌رفتن هفتصد دلار فونت‌لب می‌خریدن! 
همه‌ش ادا اطوار و پز اینکه ما خیلی آدم حسابی هستیم.
معادات کپی‌رایت دقیقن ذکر می‌کنه که هر کشوری بر اساس قوانین داخلی خودش می‌تونه اقدام کنه حتا در مورد محصولات خارجی. یعنی آمریکا همون جور که برای محصولات تولید شده در کشور خودش موظف به حمایت هست در مورد محصولات خارجیها در آمریکا هم موظف هست اما نه کمتر و نه بیشتر. اگر آلمان بگه قانون من شدیدتره و سخت‌گیری بیشتری لازم داره آمریکا الزامی به رعایتش نداره.
در مورد ایران هم تفسیرش این میشه که وقتی ما کل نرم‌افزارهای خارجی رو می‌دزدیم و هیچ کپی‌رایتی نیست در مورد محصولات خودمون هم باید همین قانون صادق باشه. این که نمیشه ما تافته جدا بافته باشیم و از محصولات دزدی برای خودمون منبع درآمد ایجاد کنیم و بعد هم یه کاربر که همین آدمها بیست سال عادتش دادن که آقا کپی کن کرک کن ایرادی نداره یه فونت رو ورداشت کپی کرد همه  بریزیم سرش. سعی کردم در واضح‌ترین حالت منظورم رو بگم :)

۴- من خب کلن تند می‌نویسم و با کنایه و گاهی طنز. دلیل اصلی این بار هم اون کامنت پلیسی زشت بود که وقتی من دارم راجع به فونتهام نظر می‌پرسم اون یارو دویده رفته گشته تو سایت من سورس و اینا رو وا کرده اومده تو فضای عمومی بدون اینکه بدونه اصن چی به چیه نوشته فونت رو وردار! بدون هیچ صحبتی راجع به اصل داستان. بعدم اون یکی پشتش اومده واسه خودش دنباله اون رو گرفته. هر چی هم بهشون مدرک و سند نشون میدی بازم حرف خودشون رو می‌زنن. فونت تهیه شده از محک رو میگه برو از مریم‌سافت اجازه بگیر!! اصن نمی‌دونه که نه تنها قانون این نیست اصلن فونت مریم‌سافت تغییر کدپوینت داده شده ست و اسکریپت نداره و نمیشه در وب استفاده بشه :))

بله بله. من سخت اصلن نمی‌گیرم ولی در برابر آدمهای همیشه حق به جانب هم واقعن نمی‌تونم سکوت کنم. چون احساس می‌کنم یکی از مشکلات اغلب موضوعات حل‌نشده همین جواب ندادن و دفاع نکردن از اندیشه خودمون هست.

ارادت

**Comment by zoghal** [comment]
من مخلوط دو پست رو پاسخ میدم:  

> من متوجه شدم که صابر جان از تعریف و تمجید خوششون نمیاد یا شاید معذب میشن :) ولی من رو کسایی که میشناسن میدونن که تعریف همین جوری نمیکنم. 

ای ای گفتی اصلا یک کارایی میکنه شاخ در میاره. برداشت من اینه که صابر تمام نیت و صعی‌اش اینه کسی رو به هر دلیلی آزرده خاطر نکنه. و بسیار درون گرا هست. 
 بزار یک انتقاد کنم : مثلا حمایتش می‌کنی، حمایت رو دوبل میکنه بر می‌گردونه به خودت.  صابر جان شما عزیز و مهربانی ، نیتت برای من کاملا آشکار شده و شکی ندارم. اما رک بگم این کارت کمی ناراحتم کرد. درسته در شرایط خوبی به سر نمی‌برم اما آن مبلغ در راستای اهدافم و بنا بر شرایط لازم بود انجام بشه. و اصلا مبلغی نبود که بخواد بهم فشار بیاره، اگر غیر از این بود اصلا همچین کاری نمی‌کردم. اما چرا حمایت کردم رو هم میزارم برایت ؟ سوال بشه کمی فکر کنی و اگر به نتیجه نرسیدی حاضر بشی اون پوسته که دوره خودت بستی و روابت اجتماعیت رو محدود کردی رو بشکنی تا بتونم به صورت صوتی بهت بگم 

> متاسفانه فوروم‌های ایرانی همون جوری که قبلن هم بهم ثابت شده بود و سالها فراری بودم ازشون تا اینکه اومدم گیت هاب و اینا، همش دنبال حاشیه و پلیس‌بازی هستن و در طول شاید ده سال گذشته دریغ از یک همفکری و انتقاد مفید. نمونه‌ش دفعه پیش بود که کلن بحث بیهوده و بی‌فایده‌ای در گرفت و وقت و انرژی همه رو هدر داد. بدیهیاتی رو باید توضیح داد که واقعن از حوصله و انرژی من خارجه.
> من هم دوباره برگشتم به دوران قبل و با فورومها و گروههای ایرانی کاری ندارم چه ایرماگ چه فونت آزاد و چه توییتر. سه تا پست تو تایپ‌دراوور خارجی گذاشتم اندازه یک سال چیز یاد گرفتم. بنابراین عاقلانه است که وقتم رو اونجا بذارم.

سیاوش جان تو دیگه خودت از قدیمی های این موضوع حساب میشی و بهتر از هر کسی از جو موجود  با خبری. متاسفانه در جامعه ما یکسری افراد به اشتباه آنقدر بزرگ میشوند که تبدیل به بت می‌شوند. اگر با این بت ها بخواهی در بیوفتی خودت نابود میشی و اگر سکوت کنی یکجات می‌سوزه. 
من طبق تجربیاتم یک راحل براش پیدا کردم. فهمیدم این انسان‌ها را باید توسط خودشون نابود کرد. برای همین روش خاصی رو در پیش گرفتم، جنگیدن با سر و صدای زیاد، آگاهی رساندن و ایجاد یک محیط آماده برای مانور این دوستان که بهم ضربه بزنند. تا اینطوری بی سوادی و جهالتشون رو علاوه بر اینکه به روی خودشون بزنم، به سایرین هم نشون بدم.

همین بهداد که این همه ادعاش میشه ببین چه سوتی داد ([اینجا](https://github.com/IranOpenFontGroup/Discussions/issues/1#issuecomment-213588158))
فونت گنجنامه در توضیحاتش فقط ریشه از ایرانین سنسز داره. و همانطور که صابر هم متذکر شده کلی تغییرات داره.  در اصل این فونت آن فونت قدیمی نیست. فقط تو توضیحاتش از ایرانین سنسز اسم آوردم.
اما این آقا بدون دقت به نظر صابر و میاد میگه «حداقلش اینکه نه شما نه هومن مهر صاحب حقوقِ این فونت نیستین و درنتیجه اجازه‌ی تغییر مجوزش رو ندارین»  . 

یا در مورد فونت دیبا که خودت به خوبی توضیح دادی و متذکر شدی وقتی طراحش آنقدر شعور و سواد نداره که حتی کپی رایتش رو شاگردش به اسم خودش کرده اصلا چرا باید از طراحش باید اجازه گرفت .

من اگر دخالتی نکردم برای این بود که بهداد فکر میکنه من فر خوردم و دیگه پایم رو از اونجا بریده(داستان دارد). در صورتی که من دارم بر اساس مهندسی معکوس و مهندسی اجتماعی نه از ایشان بلکه از تموم بت ها مدرک جمع میکنم تا یکسره کنم و این آقایان رو پس بزنم و تا جای بحث باز بشه. و درسی برای آیندگان باشه که شو من بازی تعطیل شد در این باره. 

> راستی صالح یا صابر جان اگه دوست داشتین یک گروه فونت واقعن آزاد راه اندازی کنین که اونجا همه کسایی که به فکر فونت آزاد هستن بیان. خیلی بهتره تا اونجا که بوی باندبازی میده. 

جانا حرف دل ما رو میزنی که، شاید صابر در جریان نباشه اما مومن توکه از همون سه سال پیش از خواهش و دعوت به همکاری ما باخبر بودی که :))
خانه فونت هم بر همین اساس بنا نهاده شد. در ابتدا شاید قرار بود فروشگاه فونت باشه. اما بعد از کسب تجربه و درک وضعیت موجود جامعه و نیاز به فونت و .... اسمش، هدفش، … رو عوض کردم.
قلبا آماده همکاری هستم، اما در وضعیت فعلی و بعد از این همه کار رایزنی‌های دولتی ، شبکه سازی مردمی و تبلیغات و جا انداختن اسم و ... هر گونه تغییر مسیر به واسطه یک اسم جدید  یا تغییر اسم هزینه سنگینی در بر داره. پس از این هیث بهترین گزینه این هست که شماها را دعوت کنم برای پیوستن به خانه فونت، و در این مجموعه(فعلا اسم تنها هست) مختارید به تصمیم گیری گروهی و البته کار درست. کار درست به این معنی هست که حرکت تو این مسیر نیاز به ایستادگی و تلاش و صبر بسیار هست. هر چیزی رو از هرکسی نباید قبول کرد و منطق حرف اول رو تو خونه فونت میزنه. و بعد اخلاق.

در این زمینه اگر تمایل داشتید بگید تا در تلگرام یا اسکایپ گروهی ایجاد کنیم تا صحبت کنیم.

**Comment by rastikerdar** [comment]
من در عجبم چرا این بحث فونت اینقدر حاشیه داره :)

حقیقتش دوستان من علاقه ای به صحبت در مورد دیگران ندارم. اسامی که نام می برید ( بهداد، طراح فونت دیبا، عوامل مریم سافت و...) همگی برای من مثل خود شما عزیز و مورد احترام هستند. 

صحبت هاتونو به دقت خونده ام و خب در برخی موارد موافق و برخی مخالف هستم و دغدغه شما رو درک میکنم هر چند که از وادی فونت، طراحان، شرکت ها و ... کلا بی خبرم و علاقه ای هم ندارم.

در مورد گروه هم من معتقدم گروه قلم آزاد ایران گروه خوبیه. پیشنهاد می کنم فعالیت هاتونو تحت همون گروه انجام بدین و از مشارکت و نظرات دیگر اعضا استفاده کنید. من هم نه فرصت فعالیت جدی تو این زمینه دارم و نه تخصص و کارم در حوزه گرافیک و فونت و ... هست.

از محبت و لطفی که به من دارید سپاسگزارم.
اگر موافق باشید این ایشو رو خاتمه بدیم.

**Comment by zoghal** [comment]
ممنون از پاسخت، من برای ختم این تاپیک آخرین صحبتم رو در این ضمینه با شما صابر جان میکنم. انتخاب باخودت هست دیگه و قول میدم با شما در این مورد هیچ بحثی نداشته باشم.

> من در عجبم چرا این بحث فونت اینقدر حاشیه داره :)

خیلی سادست صابر عزیز . ما یک جامعه هستیم ([این مقاله رو بخونید](http://fereidounfeiz.blogfa.com/post/2/%D9%86%D9%82%D8%B4-%D9%81%D8%B1%D8%AF-%D8%AF%D8%B1-%D8%AC%D8%A7%D9%85%D8%B9%D9%87))یکایک ما نقشی در این جامعه بر عهده داریم  و البته این نقش منتهی به خود فرد محدود نمیشود بلکه نسبت به سایر افراد هم مسولیت هایی داریم.
داستان فونت بخشی کوچکی از هزاران مشکل موجود در کشور ما هست. متاسفانه عده‌ای  قبلتر از ما یا وظایف خودشان را فراموش کردند یا به قصد یا  غیر عمد کمکاری کردند یا همچون شما به هر دلیل و تفکری که دارند معتقدا  اگر من سرم رو بندازم پایین و کار خودم رو انجام بدم  به این معنی هست  کهمسولیتم رو کمال و تمام نسب به جامعه خودم انجام دادم و نیاز نیست کار دیگری انجام بدم.
 در نهایت این مشکلات  آنقدر روب هم تلمبار شده  تا به ما رسیده و متاسفانه  اکثر افراد جامعه فعلی  مسئولین رو مقصر می‌دونند. در این حین افرادی روی کار اومدند  که از موقعیت بوجود آمده برای خودشان جا و مقامی درست کردند و بولد شدند. مثل دامون خانجانزاده و نوچه هاش.

بزار  چند سوال بپرسم : 
۱- شما چطور تونستی از صفر به حدی برسی که یک فونت در چند وزن ردیف کنی اما دامون نسته؟
۲- اصلا چرا  یک فونت آنقدر زمان برده ؟ ایا می‌دونی به گفته بهداد عابدی چند نفر دارند روی فونت کار می‌کنند؟([تصویر۱ ](https://dl.dropboxusercontent.com/u/5698921/pfont/esfahbod.png)\- [تصویر۲ ](https://dl.dropboxusercontent.com/u/5698921/pfont/esfahbod.png)\- تصویر ۳)
۳-  چرا سفارشی که تموم نشده سفارش دیگه ای گرفته و مهمتر از همه چه تور است که بهداد عابدی کارش به جایی میرسه که برای دامون و برای یک فونت دیگر کرنینگ انجام میده([تصویر](https://dl.dropboxusercontent.com/u/5698921/pfont/madrak1.png)) و بدبختی اینجاست که این آقا کارش به جایی رسیده که قصد داشته با من کار کنه :)) اما چون من شلوغ کردم کار نکردم ([تصویر](https://dl.dropboxusercontent.com/u/5698921/pfont/hamkari.png))

ایا از نظر تو کار پروژه پی فونت اخلاقی و درست هست؟ ایا این توهین به مشارکت کننده‌هاش نیست؟ ایا این باعث سلب اعتماد دیگران نمیشه و در نهایت آسیبش به خود شما نمیرسه؟ ایا با سکوت درست میشه؟ 

> در مورد گروه هم من معتقدم گروه قلم آزاد ایران گروه خوبیه. پیشنهاد می کنم فعالیت هاتونو تحت همون گروه انجام بدین و از مشارکت و نظرات دیگر اعضا استفاده کنید. 

خوب بود تا پای بهداد اسفهبد باز شد! اسمش رو گذاشتم استاد اخلاق کامینیتی و مدافع حقوق دامی جون . یکی دیگه از مشکلات فونت فارسی شومن‌های فونت فارسی هستند کسانی که یک زمانی یک کاری کردند ول کردن به امان خدا، حالا که موضوع داغ شده سر و کله شون پیدا شده و کاسه داغتر از آش شدند

 تو تصاویر میبینی که بهداد اسفهبد پشت سر پی فونت هست. ایا با وضعیت فعلی این پروژه و اینکه  ایشان هیچ کاری انجام نمیده  و سکوت کردند دارند کار اخلاقی  انجام میدن؟

این ویدیو رو ببین ([کلیپ برخورد بهداد](https://www.youtube.com/watch?v=8NoIL3QNuQA&feature=youtu.be))  اکمی با شومنی هاش آشنا شو. 
و این سوالات رو از خودت بپرس : 
۱- در ۱۵ سال کذشته کجا بوده، چی کرده و چند فونت در خروجی‌هاش دیده میشه؟ که به خودش اجازه همچین برخوردی میده؟
۲-  بچه‌هایی که میگه (همون نوچه های دامون) بعد از گذشت یک سال چند فونت عرضه کردند و من و شما چندتا؟ اصلا ما چطور تونستیم اینها نتونستند؟

۳-  این اقا که مدعی فلسفه آزاد در آموزش و ... هست. چرا تا الان سوال تو رو در مورد استاندارد طراحی حروف پاسخ نداده؟

۴- چرا این آقا که در جریان پروژه من بوده از ابتدا یکباره این برخورد رو میکنه. (شهاب اینجا شاهد هست من چقدر از گرافیست ها خواهش و التماس کردم بییاید کمک ، بیایید همکاری)

۵- بزار ببینیم شما رو که بچه خوبی بوده چه طور حمایت میکنه :دی دو سال پیش به من گفتش نمی‌تونم برای افراد که توی ایران هستند کاری انجام بدم :)) .

۶- این [ویدیو](https://www.youtube.com/watch?v=nGB3v6E6ytU&list=PLDauK1xi4ct2tsWwuOfuVAZLUHU9SQPvj&index=5) هم باحاله اعتراف میکنه فارسی زیاد استفاده نمیکنه.

بگذریم حرف برای گفتن زیاد هست. فقط یک سوال به این کار شما چی میگید؟ [نگاه کن](https://www.youtube.com/watch?v=pTBKUvrUxQk&list=PLDauK1xi4ct2tsWwuOfuVAZLUHU9SQPvj&index=6)

ختم کلام :  

> من هم نه فرصت فعالیت جدی تو این زمینه دارم و نه تخصص و کارم در حوزه گرافیک و فونت و ... هست.

دادشم  صابر عزیز بهانه‌ات رو عوض کن خیلی تکراری شده. تو دیگه معتاد حروف حساب میشی کنار برو نیستی . با این بهونه ها اگر سعی داری خودت رو گول بزنی و چشمت روی حقیقت ببندی و اصلا هرچیزی که تو ذهنته ....
 از نظر من هیچ اشکالی نداره. چون من و شما رو  در نهایت تو یک کفن قرار نمیدند. پس مواظب حق ناس باش،  شاید در خیلی از موارد واقعا  در حال حاضر تو ایران کاری از دست من  و شما بر نیاد. اما در این مورد یعنی فونت بر میاد سعی کردیم و تونستیم.  و وظیفه من و شماست که یک دست بشیم و جلو تکرار پی فونت ها رو بگیریم. نه سکوت کنیم و کار خودمون رو ..

اگر باز صحبت‌های من باعث ناراحتید شد. خیلی خیلی  عذر خواهی میکنم. وظیفه خودم می‌دونستم این موارد رو به اطلاع برسانم.   انتخاب راه با خودت هست. دوست خوبم.

شاد و پیروز باشی

**Comment by rastikerdar** [comment]
آقا صالح دیدگاه من با شما تفاوت بسیاری دارد و متاسفانه نمی توانم با شما همراه باشم.

 فقط در مورد بخش آخر که به من مربوط میشد باید عرض کنم که ماه های نخستی که فونت ها را می ساختم همزمان ایده های مختلفی به ذهنم می رسید که دو تا فونت رو به صورت نصفه و نیمه انجام دادم. تا اینکه بعد از یک وقفه نسبتا طولانی بالاخره تصمیم به اتمامشان گرفتم و خب اکنون خوشبختانه با انجامش ذهنم آرام گرفته و البته هیچ تمایلی هم برای کارهای جدید ندارم. بر خلاف شما من علاقه و اعتیادی هم به حروف فارسی و این موضوعات ندارم.
شاید اگر کسی پیشنهاد میلیاردی می داد کار جدید قبول می کردم ;)

.سلامت باشید

پس من با اجازه این ایشو رو می بندم.
