### ISSUE TITLE
اشکال در فاصله بین حروف

### ISSUE THREAD

**Issue by rastikerdar** [rastikerdar/sahel-font#9]
آقای علی یعقوبی گزارش دادند که در سیستم عاملشان بین حروف فاصله می افتد:
IOS
![cpbwwpuuiaarcah jpg large](https://cloud.githubusercontent.com/assets/3116038/17612156/f41011ca-6063-11e6-9c82-70c262c8e62f.jpeg)

**Comment by rastikerdar** [comment]
به اندازه قابل توجهی در نسخه جدید ناحیه همپوشانی افزایش یافت.

**Comment by erfsober** [comment]
سلام.
در فایرفاکس هم این مشکل رویت میشه.
![image](https://user-images.githubusercontent.com/39940319/62032278-87d1e480-b1fe-11e9-8f72-f403ec554c97.png)

**Comment by rastikerdar** [comment]
فکر می‌کنم شما در قسمت استایل فاصله بین حروف رو افزایش دادین که باید اون رو صفر کنید.
CSS:‍ `letter-spacing: 0px;`
